### ISSUE TITLE
grid aggregation

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality-spatial#39]
using output of #38 
aggregate 

- [x]  deaths
- [x] population 

matching the analysis strata of deaths
so` year X age X sex` for sure as first cut
later may be extended to nationality, sep, others?

**Comment by gkonstantinoudis** [comment]
the ethnicity will be nice to use rather as a covariate, if we include covariates, but for now leave it like this because we can easily aggregate when we have the long format.

**Comment by RPanczak** [comment]
Thanks Akis!
Not sure what you exactly mean by ethnicity here?
In the delivered data (monthly deaths by community) we only have binary *nationality* indicator.
With SNC we could (potentially) ask for more detailed information. I'd assume it's still about nationality not ethnicity though.
